## Without Pipeline

In [76]:
import numpy as np
import pandas as pd 
from sklearn.model_selection import train_test_split # to test data
from sklearn.impute import SimpleImputer # to handle missing data
from sklearn.preprocessing import OneHotEncoder # to handle categorical columns
from sklearn.preprocessing import MinMaxScaler # For scalling
from sklearn.tree import DecisionTreeClassifier # For prediction
from sklearn.pipeline import Pipeline # to connect everything act like a chain

In [77]:
df = pd.read_csv(r"C:\Users\Asus4\Downloads\Mlopps\train.csv")

In [78]:
df.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [79]:
df.drop(columns= ['PassengerId','Name','Ticket','Cabin'],inplace=True)

In [80]:
df.head()

   Survived  Pclass     Sex  ...  Parch     Fare  Embarked
0         0       3    male  ...      0   7.2500         S
1         1       1  female  ...      0  71.2833         C
2         1       3  female  ...      0   7.9250         S
3         1       1  female  ...      0  53.1000         S
4         0       3    male  ...      0   8.0500         S

[5 rows x 8 columns]

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    object
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Fare      891 non-null    float64
 7   Embarked  889 non-null    object
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB

In [82]:
df.Embarked.unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [83]:
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['Survived']),df['Survived'],test_size=0.2,random_state=42)

In [84]:
X_train.head()

     Pclass     Sex   Age  ...  Parch     Fare  Embarked
331       1    male  45.5  ...      0  28.5000         S
733       2    male  23.0  ...      0  13.0000         S
382       3    male  32.0  ...      0   7.9250         S
704       3    male  26.0  ...      0   7.8542         S
813       3  female   6.0  ...      2  31.2750         S

[5 rows x 7 columns]

In [85]:
y_train.head()

331    0
733    0
382    0
704    0
813    0
Name: Survived, dtype: int64

In [86]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

#### Handling Missing Data--SimpleImputer

In [87]:
# Applying imputation

si_age = SimpleImputer()
si_embarked = SimpleImputer(strategy='most_frequent')

X_train_age = si_age.fit_transform(X_train[['Age']])
X_train_embarked = si_embarked.fit_transform(X_train[['Embarked']])

X_test_age = si_age.transform(X_test[['Age']])
X_test_embarked = si_embarked.transform(X_test[['Embarked']])

In [70]:
X_train_age

array([[45.5       ],
       [23.        ],
       [32.        ],
       [26.        ],
       [ 6.        ],
       [24.        ],
       [45.        ],
       [29.        ],
       [29.49884615],
       [29.49884615],
       [42.        ],
       [36.        ],
       [33.        ],
       [17.        ],
       [29.        ],
       [50.        ],
       [35.        ],
       [38.        ],
       [34.        ],
       [17.        ],
       [11.        ],
       [61.        ],
       [30.        ],
       [ 7.        ],
       [63.        ],
       [20.        ],
       [29.49884615],
       [29.        ],
       [36.        ],
       [29.49884615],
       [50.        ],
       [27.        ],
       [30.        ],
       [33.        ],
       [29.49884615],
       [29.49884615],
       [ 2.        ],
       [25.        ],
       [51.        ],
       [25.        ],
       [29.49884615],
       [29.49884615],
       [24.        ],
       [18.        ],
       [29.49884615],
       [25.        ],
       [24.        ],
       [22.        ],
       [ 0.92      ],
       [24.        ],
       [26.        ],
       [34.        ],
       [21.        ],
       [29.49884615],
       [29.49884615],
       [29.49884615],
       [22.        ],
       [62.        ],
       [18.        ],
       [42.        ],
       [57.        ],
       [19.        ],
       [42.        ],
       [29.49884615],
       [20.        ],
       [34.5       ],
       [28.        ],
       [29.49884615],
       [23.        ],
       [22.        ],
       [52.        ],
       [30.        ],
       [36.5       ],
       [29.49884615],
       [22.        ],
       [50.        ],
       [27.        ],
       [22.        ],
       [51.        ],
       [36.        ],
       [29.        ],
       [22.        ],
       [50.        ],
       [40.        ],
       [27.        ],
       [29.49884615],
       [65.        ],
       [17.        ],
       [28.        ],
       [ 4.        ],
       [29.49884615],
       [ 1.        ],
       [36.        ],
       [43.        ],
       [38.        ],
       [31.        ],
       [29.        ],
       [18.        ],
       [29.49884615],
       [39.        ],
       [39.        ],
       [26.        ],
       [20.        ],
       [29.49884615],
       [49.        ],
       [23.        ],
       [ 1.        ],
       [29.49884615],
       [29.49884615],
       [ 3.        ],
       [ 4.        ],
       [19.        ],
       [40.5       ],
       [ 1.        ],
       [29.49884615],
       [21.        ],
       [54.        ],
       [29.49884615],
       [25.        ],
       [26.        ],
       [22.        ],
       [31.        ],
       [49.        ],
       [19.        ],
       [24.        ],
       [16.        ],
       [25.        ],
       [39.        ],
       [47.        ],
       [60.        ],
       [24.        ],
       [29.49884615],
       [27.        ],
       [29.49884615],
       [38.        ],
       [44.        ],
       [21.        ],
       [24.        ],
       [45.        ],
       [ 8.        ],
       [ 8.        ],
       [29.49884615],
       [32.        ],
       [50.        ],
       [21.        ],
       [50.        ],
       [23.        ],
       [32.        ],
       [29.49884615],
       [21.        ],
       [29.49884615],
       [25.        ],
       [15.        ],
       [31.        ],
       [25.        ],
       [54.        ],
       [28.        ],
       [38.        ],
       [41.        ],
       [33.        ],
       [52.        ],
       [16.        ],
       [20.        ],
       [ 9.        ],
       [29.49884615],
       [29.49884615],
       [29.49884615],
       [54.        ],
       [26.        ],
       [60.        ],
       [29.49884615],
       [44.        ],
       [20.        ],
       [29.49884615],
       [16.        ],
       [43.        ],
       [17.        ],
       [37.        ],
       [62.        ],
       [ 8.        ],
       [32.        ],
       [20.        ],
       [28.        ],
       [21.        ],
       [37.        ],
       [17.        ],
       [29.49884615],
       [46.        ],
       [29.49884615],
       [24.        ],
       [29.        ],
       [56.        ],
       [31.        ],
       [29.49884615],
       [32.        ],
       [33.        ],
       [59.        ],
       [58.        ],
       [29.49884615],
       [ 3.        ],
       [29.49884615],
       [16.        ],
       [45.        ],
       [43.        ],
       [30.        ],
       [28.5       ],
       [24.        ],
       [30.        ],
       [36.        ],
       [25.        ],
       [29.49884615],
       [50.        ],
       [ 0.75      ],
       [24.        ],
       [24.        ],
       [35.        ],
       [30.        ],
       [23.        ],
       [29.49884615],
       [27.        ],
       [55.        ],
       [35.        ],
       [29.49884615],
       [29.49884615],
       [29.49884615],
       [23.        ],
       [29.49884615],
       [23.        ],
       [51.        ],
       [33.        ],
       [29.        ],
       [29.49884615],
       [29.49884615],
       [ 2.        ],
       [14.        ],
       [54.        ],
       [15.        ],
       [22.        ],
       [27.        ],
       [29.49884615],
       [29.49884615],
       [28.        ],
       [39.        ],
       [ 2.        ],
       [24.        ],
       [32.        ],
       [45.5       ],
       [ 8.        ],
       [26.        ],
       [29.        ],
       [45.        ],
       [36.        ],
       [29.49884615],
       [ 4.        ],
       [16.        ],
       [58.        ],
       [40.5       ],
       [25.        ],
       [29.49884615],
       [51.        ],
       [29.49884615],
       [17.        ],
       [29.49884615],
       [40.        ],
       [25.        ],
       [47.        ],
       [29.49884615],
       [44.        ],
       [23.        ],
       [18.        ],
       [29.        ],
       [12.        ],
       [11.        ],
       [22.        ],
       [19.        ],
       [22.        ],
       [33.        ],
       [56.        ],
       [ 1.        ],
       [22.        ],
       [29.49884615],
       [29.49884615],
       [ 7.        ],
       [ 4.        ],
       [70.5       ],
       [18.        ],
       [20.        ],
       [24.        ],
       [29.49884615],
       [34.        ],
       [29.49884615],
       [31.        ],
       [30.        ],
       [18.        ],
       [ 9.        ],
       [39.        ],
       [33.        ],
       [70.        ],
       [24.        ],
       [58.        ],
       [21.        ],
       [17.        ],
       [28.        ],
       [24.        ],
       [29.49884615],
       [29.49884615],
       [42.        ],
       [18.        ],
       [ 2.        ],
       [34.        ],
       [ 3.        ],
       [58.        ],
       [32.        ],
       [31.        ],
       [29.49884615],
       [27.        ],
       [11.        ],
       [23.        ],
       [40.        ],
       [29.49884615],
       [28.        ],
       [28.        ],
       [29.49884615],
       [19.        ],
       [30.        ],
       [20.        ],
       [28.        ],
       [36.        ],
       [29.49884615],
       [24.        ],
       [28.5       ],
       [24.        ],
       [42.        ],
       [54.        ],
       [25.        ],
       [ 7.        ],
       [25.        ],
       [27.        ],
       [24.        ],
       [29.49884615],
       [28.        ],
       [19.        ],
       [22.        ],
       [29.49884615],
       [29.49884615],
       [42.        ],
       [50.        ],
       [ 3.        ],
       [29.49884615],
       [18.        ],
       [18.        ],
       [44.        ],
       [29.49884615],
       [29.49884615],
       [29.49884615],
       [16.        ],
       [29.49884615],
       [22.        ],
       [ 4.        ],
       [29.49884615],
       [24.        ],
       [30.        ],
       [29.        ],
       [24.        ],
       [45.        ],
       [32.        ],
       [21.        ],
       [35.        ],
       [29.49884615],
       [29.49884615],
       [36.        ],
       [41.        ],
       [23.        ],
       [34.        ],
       [29.49884615],
       [29.49884615],
       [15.        ],
       [29.49884615],
       [18.        ],
       [30.        ],
       [32.        ],
       [ 4.        ],
       [ 2.        ],
       [29.49884615],
       [29.49884615],
       [48.        ],
       [31.        ],
       [47.        ],
       [26.        ],
       [ 9.        ],
       [19.        ],
       [29.49884615],
       [22.        ],
       [29.49884615],
       [28.        ],
       [24.        ],
       [17.        ],
       [29.49884615],
       [29.49884615],
       [21.        ],
       [51.        ],
       [ 3.        ],
       [ 0.75      ],
       [29.49884615],
       [34.        ],
       [18.        ],
       [44.        ],
       [29.49884615],
       [29.49884615],
       [37.        ],
       [21.        ],
       [36.        ],
       [32.        ],
       [29.49884615],
       [26.        ],
       [80.        ],
       [55.5       ],
       [60.        ],
       [29.49884615],
       [18.        ],
       [14.5       ],
       [19.        ],
       [ 4.        ],
       [33.        ],
       [21.        ],
       [10.        ],
       [47.        ],
       [ 2.        ],
       [29.        ],
       [22.        ],
       [28.        ],
       [29.49884615],
       [26.        ],
       [33.        ],
       [27.        ],
       [27.        ],
       [34.        ],
       [29.49884615],
       [30.        ],
       [30.        ],
       [29.49884615],
       [29.49884615],
       [53.        ],
       [32.        ],
       [52.        ],
       [52.        ],
       [39.        ],
       [ 2.        ],
       [44.        ],
       [51.        ],
       [39.        ],
       [46.        ],
       [17.        ],
       [30.        ],
       [ 9.        ],
       [27.        ],
       [21.        ],
       [29.49884615],
       [26.        ],
       [ 3.        ],
       [48.        ],
       [36.        ],
       [29.49884615],
       [32.5       ],
       [33.        ],
       [22.        ],
       [19.        ],
       [74.        ],
       [42.        ],
       [40.        ],
       [35.        ],
       [24.        ],
       [39.        ],
       [32.5       ],
       [ 1.        ],
       [34.        ],
       [64.        ],
       [25.        ],
       [29.49884615],
       [ 1.        ],
       [45.        ],
       [31.        ],
       [21.        ],
       [25.        ],
       [15.        ],
       [26.        ],
       [30.        ],
       [24.        ],
       [35.        ],
       [70.        ],
       [29.49884615],
       [21.        ],
       [18.        ],
       [29.49884615],
       [ 1.        ],
       [29.49884615],
       [26.        ],
       [25.        ],
       [29.49884615],
       [20.        ],
       [54.        ],
       [22.        ],
       [59.        ],
       [54.        ],
       [27.        ],
       [31.        ],
       [22.        ],
       [33.        ],
       [ 6.        ],
       [ 5.        ],
       [39.        ],
       [24.5       ],
       [54.        ],
       [29.49884615],
       [29.49884615],
       [30.        ],
       [29.49884615],
       [35.        ],
       [21.        ],
       [32.        ],
       [16.        ],
       [22.        ],
       [29.49884615],
       [38.        ],
       [29.49884615],
       [25.        ],
       [33.        ],
       [29.49884615],
       [18.        ],
       [29.49884615],
       [29.49884615],
       [ 2.        ],
       [ 0.42      ],
       [26.        ],
       [41.        ],
       [48.        ],
       [48.        ],
       [48.        ],
       [ 4.        ],
       [39.        ],
       [33.        ],
       [29.        ],
       [49.        ],
       [29.49884615],
       [29.49884615],
       [42.        ],
       [36.        ],
       [61.        ],
       [18.        ],
       [18.        ],
       [ 0.67      ],
       [32.        ],
       [29.49884615],
       [29.49884615],
       [29.49884615],
       [16.        ],
       [31.        ],
       [48.        ],
       [22.        ],
       [13.        ],
       [32.        ],
       [28.        ],
       [46.        ],
       [28.        ],
       [42.        ],
       [35.        ],
       [ 2.        ],
       [31.        ],
       [29.49884615],
       [29.49884615],
       [19.        ],
       [20.        ],
       [14.        ],
       [34.        ],
       [29.49884615],
       [29.49884615],
       [51.        ],
       [29.49884615],
       [29.49884615],
       [29.49884615],
       [28.        ],
       [25.        ],
       [19.        ],
       [35.        ],
       [35.        ],
       [ 9.        ],
       [20.        ],
       [42.        ],
       [30.        ],
       [29.49884615],
       [21.        ],
       [47.        ],
       [25.        ],
       [16.        ],
       [45.        ],
       [38.        ],
       [56.        ],
       [29.49884615],
       [31.        ],
       [30.        ],
       [29.49884615],
       [14.        ],
       [16.        ],
       [40.        ],
       [55.        ],
       [19.        ],
       [45.        ],
       [36.        ],
       [27.        ],
       [49.        ],
       [41.        ],
       [19.        ],
       [33.        ],
       [27.        ],
       [29.49884615],
       [35.        ],
       [29.        ],
       [30.        ],
       [34.        ],
       [29.        ],
       [19.        ],
       [35.        ],
       [29.49884615],
       [40.        ],
       [62.        ],
       [25.        ],
       [26.        ],
       [18.        ],
       [34.        ],
       [48.        ],
       [28.        ],
       [24.        ],
       [17.        ],
       [38.        ],
       [29.49884615],
       [40.        ],
       [22.        ],
       [ 2.        ],
       [28.        ],
       [18.        ],
       [28.        ],
       [19.        ],
       [29.49884615],
       [60.        ],
       [20.        ],
       [45.        ],
       [29.49884615],
       [24.        ],
       [29.49884615],
       [29.49884615],
       [39.        ],
       [26.        ],
       [24.        ],
       [36.        ],
       [37.        ],
       [29.49884615],
       [28.        ],
       [19.        ],
       [43.        ],
       [25.        ],
       [47.        ],
       [16.        ],
       [ 0.83      ],
       [22.        ],
       [19.        ],
       [28.        ],
       [14.        ],
       [36.        ],
       [29.        ],
       [42.        ],
       [29.49884615],
       [27.        ],
       [29.        ],
       [ 5.        ],
       [22.        ],
       [29.49884615],
       [30.        ],
       [62.        ],
       [34.        ],
       [28.        ],
       [29.49884615],
       [44.        ],
       [45.        ],
       [19.        ],
       [18.        ],
       [31.        ],
       [29.49884615],
       [21.        ],
       [25.        ],
       [32.        ],
       [30.        ],
       [40.        ],
       [33.        ],
       [36.        ],
       [47.        ],
       [34.        ],
       [19.        ],
       [29.49884615],
       [50.        ],
       [29.49884615],
       [29.49884615],
       [29.49884615],
       [29.49884615],
       [35.        ],
       [35.        ],
       [18.        ],
       [16.        ],
       [21.        ],
       [29.49884615],
       [41.        ],
       [14.        ],
       [21.        ]])

In [71]:
X_train_embarked

array([['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['Q'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['Q'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['Q'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['Q'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['S'],
       ['Q'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['S'],
       ['C'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['Q'],
       ['C'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['C'],
       ['S'],
       ['C'],
       ['Q'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['Q'],
       ['Q'],
       ['C'],
       ['Q'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['C'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['Q'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['Q'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['Q'],
       ['S'],
       ['C'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['Q'],
       ['S'],
       ['S'],
       ['C'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['Q'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['Q'],
       ['S'],
       ['Q'],
       ['Q'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['Q'],
       ['S'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S']], dtype=object)

#### Working on Categorical column -- OneHotEnconding

In [88]:
ohe_sex = OneHotEncoder(sparse_output=False,handle_unknown='ignore')
ohe_embarked = OneHotEncoder(sparse_output=False,handle_unknown='ignore')

X_train_sex = ohe_sex.fit_transform(X_train[['Sex']])
X_train_embarked = ohe_embarked.fit_transform(X_train_embarked)

X_test_sex = ohe_sex.transform(X_test[['Sex']])
X_test_embarked = ohe_embarked.transform(X_test_embarked)

In [89]:
X_train_embarked

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]], shape=(712, 3))

In [90]:
X_train_rem = X_train.drop(columns=['Sex','Age','Embarked'])

In [91]:
X_test_rem = X_test.drop(columns=['Sex','Age','Embarked'])

In [92]:
X_train_transformed = np.concatenate((X_train_rem,X_train_age,X_train_sex,X_train_embarked),axis=1)
X_test_transformed = np.concatenate((X_test_rem,X_test_age,X_test_sex,X_test_embarked),axis=1)

In [93]:
X_test_transformed.shape

(179, 10)

In [94]:
clf = DecisionTreeClassifier()
clf.fit(X_train_transformed,y_train)

DecisionTreeClassifier()

In [95]:
y_pred = clf.predict(X_test_transformed)
y_pred

array([0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1])

In [96]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7877094972067039

In [97]:
import pickle

In [98]:
pickle.dump(ohe_sex,open('models/ohe_sex.pkl','wb'))
pickle.dump(ohe_embarked,open('models/ohe_embarked.pkl','wb'))
pickle.dump(clf,open('models/clf.pkl','wb'))

FileNotFoundError: [Errno 2] No such file or directory: 'models/ohe_sex.pkl'

In [99]:
import pickle
import numpy as np

In [ ]:
ohe_sex = pickle.load(open('models/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl','rb'))
clf = pickle.load(open('models/clf.pkl','rb'))

In [ ]:
# Assume user input
# Pclass/gender/age/SibSp/Parch/Fare/Embarked
test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'],dtype=object).reshape(1,7)

In [ ]:
test_input

In [ ]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

In [ ]:
test_input_sex

In [ ]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

In [ ]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [ ]:
test_input_embarked

In [ ]:
test_input_age = test_input[:,2].reshape(1,1)

In [ ]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)

In [ ]:
test_input_transformed.shape

In [ ]:
clf.predict(test_input_transformed)

## Using Pipeline

In [100]:
import numpy as np
import pandas as pd

In [132]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer #-takes list of tuples as a input
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline,make_pipeline
from sklearn.feature_selection import SelectKBest,chi2
from sklearn.tree import DecisionTreeClassifier

In [102]:
df = pd.read_csv(r"C:\Users\Asus4\Downloads\Mlopps\train.csv")

In [103]:
df.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [104]:
df.drop(columns=['PassengerId','Name','Ticket','Cabin'],inplace=True)

In [105]:
# Step 1 -> train/test/split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['Survived']),
                                                 df['Survived'],
                                                 test_size=0.2,
                                                random_state=42)

In [106]:
X_train.head()

     Pclass     Sex   Age  ...  Parch     Fare  Embarked
331       1    male  45.5  ...      0  28.5000         S
733       2    male  23.0  ...      0  13.0000         S
382       3    male  32.0  ...      0   7.9250         S
704       3    male  26.0  ...      0   7.8542         S
813       3  female   6.0  ...      2  31.2750         S

[5 rows x 7 columns]

In [107]:
y_train.sample(5)

183    1
155    0
768    0
11     1
411    0
Name: Survived, dtype: int64

In [108]:
# imputation transformer - takes list of tuples as a input 
trf1 = ColumnTransformer([
    ('impute_age',SimpleImputer(),[2]),
    ('impute_embarked',SimpleImputer(strategy='most_frequent'),[6])
],remainder='passthrough')

In [110]:
# one hot encoding
trf2 = ColumnTransformer([
    ('ohe_sex_embarked',OneHotEncoder(sparse_output=False,handle_unknown='ignore'),[1,6])
],remainder='passthrough')

In [111]:
trf3 = ColumnTransformer([
    ('scale',MinMaxScaler(),slice(0,10))
])

In [112]:
# Feature selection
trf4 = SelectKBest(score_func=chi2,k=8)

In [113]:
trf5 = DecisionTreeClassifier()

### Pipeline creation

In [114]:
pipe = Pipeline([
    ('trf1',trf1),
    ('trf2',trf2),
    ('trf3',trf3),
    ('trf4',trf4),
    ('trf5',trf5)
])

### Pipeline Vs make_pipeline
###### Pipeline requires naming of steps, make_pipeline does not.

###### (Same applies to ColumnTransformer vs make_column_transformer)

In [115]:
# Alternate Syntax
pipe = make_pipeline(trf1,trf2,trf3,trf4,trf5)

In [116]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('columntransformer-1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('impute_age', SimpleImputer(),
                                                  [2]),
                                                 ('impute_embarked',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  [6])])),
                ('columntransformer-2',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe_sex_embarked',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [1, 6])])),
                ('columntransformer-3',
                 ColumnTransformer(transformers=[('scale', MinMaxScaler(),
                                                  slice(0, 10, None))])),
                ('selectkbest',
                 SelectKBest(k=8,
                             score_func=<function chi2 at 0x00000275F2338A40>)),
                ('decisiontreeclassifier', DecisionTreeClassifier())])

### Explore the Pipeline

In [145]:
pipe.named_steps['columntransformer-2'].transformers_

[('ohe_sex_embarked',
  OneHotEncoder(handle_unknown='ignore', sparse_output=False),
  [1, 6]),
 ('remainder',
  FunctionTransformer(accept_sparse=True, check_inverse=False,
                      feature_names_out='one-to-one'),
  [0, 2, 3, 4, 5])]

In [146]:
# For BackTrack or postnatal 
imputer = pipe.named_steps['columntransformer-2'].transformers_[1][1]

In [148]:
print(type(imputer))
print(imputer.statistics_)

<class 'sklearn.preprocessing._function_transformer.FunctionTransformer'>

AttributeError: 'FunctionTransformer' object has no attribute 'statistics_'

In [117]:
# Display Pipeline

from sklearn import set_config
set_config(display='diagram')

In [118]:
# Predict
y_pred = pipe.predict(X_test)

In [119]:
y_pred

array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0])

In [120]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6256983240223464

## Cross Validation using Pipeline

In [121]:
# cross validation using cross_val_score
from sklearn.model_selection import cross_val_score
cross_val_score(pipe, X_train, y_train, cv=5, scoring='accuracy').mean()

np.float64(0.6391214419383433)

### GridSearch using Pipeline

In [124]:
# gridsearchcv
params = {
    'decisiontreeclassifier__max_depth': [1, 2, 3, 4, 5, None]
}

In [125]:
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(pipe, params, cv=5, scoring='accuracy')
grid.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('columntransformer-1',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('impute_age',
                                                                         SimpleImputer(),
                                                                         [2]),
                                                                        ('impute_embarked',
                                                                         SimpleImputer(strategy='most_frequent'),
                                                                         [6])])),
                                       ('columntransformer-2',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('ohe_sex_embarked',
                                                                         OneHotEncoder(handle_unkno...,
                                                                                       sparse_output=False),
                                                                         [1,
                                                                          6])])),
                                       ('columntransformer-3',
                                        ColumnTransformer(transformers=[('scale',
                                                                         MinMaxScaler(),
                                                                         slice(0, 10, None))])),
                                       ('selectkbest',
                                        SelectKBest(k=8,
                                                    score_func=<function chi2 at 0x00000275F2338A40>)),
                                       ('decisiontreeclassifier',
                                        DecisionTreeClassifier())]),
             param_grid={'decisiontreeclassifier__max_depth': [1, 2, 3, 4, 5,
                                                               None]},
             scoring='accuracy')

In [126]:
grid.best_score_

np.float64(0.6391214419383433)

In [149]:
grid.best_params_

{'decisiontreeclassifier__max_depth': 2}

## Exporting the Pipeline

In [127]:
# export 
import pickle
pickle.dump(pipe,open('pipe.pkl','wb'))

## Prdeiction

In [128]:
import pickle
import numpy as np

In [129]:
pipe = pickle.load(open('pipe.pkl','rb'))

In [130]:
# Assume user input
test_input2 = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'],dtype=object).reshape(1,7)

In [131]:
pipe.predict(test_input2)

C:\Users\Asus4\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(
C:\Users\Asus4\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(

array([0])